### ISSUE TITLE
Add this package to the list of GAP packages on GitHub

### ISSUE THREAD

**Issue by olexandr-konovalov** [isadofschi/smallcancellation#1]
It was good to discover this repository. We maintain a list of all GAP packages with public source code repositories at https://gap-packages.github.io/ - would you be happy for me to add your package to the list?

**Comment by olexandr-konovalov** [comment]
As well as other three packages that are listed on your homepage - http://mate.dm.uba.ar/~isadofschi/.

We also have Travis CI tests for packages not (yet?) redistributed with GAP at https://github.com/gap-infra/gap-docker-pkg-tests-master-devel and https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.11-devel - since you packages have tests, you're welcome to submit a PR and add them to that tests.

**Comment by isadofschi** [comment]
Thank you! It would be great if the packages are listed. I spoke with the other authors of the Posets package and they also agree.

I will try to make the necessary changes to integrate the tests with Travis.

**Comment by olexandr-konovalov** [comment]
Thanks - done!
